### ISSUE TITLE
Markings in the citygml version 2.0 export

### ISSUE THREAD

**Issue by ChBeil** [tum-gis/rtron#20]
Information on markings is currently not transported into the CityGML version 2.0 export. Markings could/should be included as "AuxiliaryTrafficAreas" in CityGML v 2.0.

**Comment by benediktschwab** [comment]
Road markings are now also transformed to CityGML2 as AuxiliaryTrafficAreas since fe43ed1. 

For documentation:
OpenDRIVE road markings can have a width of zero, which are transformed into objects with a line geometry representation. This is not supported for AuxiliaryTrafficAreas in CityGML2.
If the road markings represented by line geometries are needed, the derived CityGML3 dataset contains them.
