### ISSUE TITLE
Objects in CityGML and 3DCityDB should have the same gml_id

### ISSUE THREAD

**Issue by joergsi** [tum-gis/rtron#3]
When working with CityGML and 3DCityDB simoultaneously it is helpful to have correspondent gml_ids.

**Comment by benediktschwab** [comment]
Hi Jörg,

the gml ids are currently generated in a random manner. This leads to completely new ids for every transformation run.
I think that stable ids could be achieved by pseudo random id generations that depend on the road id and object id of an OpenDRIVE.
I will have a look into that.

Best regards
Benedikt

**Comment by benediktschwab** [comment]
Hi @joergsi ,

the CityGML ids are now generated as hash of the road object id, road id, lane id and the OpenDRIVE dataset itself.
If anything is changed within the dataset, new CityGML ids are generated.
Otherwise a transformation run will generate the same ids for each object as the previous run.

Best regards
Benedikt

**Comment by joergsi** [comment]
Great! Thank you.
