### ISSUE TITLE
Missing connections to bidirectional TrafficSpace objects

### ISSUE THREAD

**Issue by CodeMazeSolver** [tum-gis/rtron#37]
# Current situation
![image](https://github.com/tum-gis/rtron/assets/44395230/526a58ce-f044-4be5-8f4e-88987ba3c579)

The screenshot shows a narrow part of a road in the Grafing dataset. Here, two lanes in different directions have to share the road in a single element for a short distance due to a bottleneck. The lane on top is connected correctly as its the primary connection path in this example. However, the lane on the bottom gets narrower and narrower closer to the bidirectional segment. This leads to a dead end with no connection between the two ends of the lower lane.

# Proposed solution
![image](https://github.com/tum-gis/rtron/assets/44395230/84e1e1a4-11c0-49f8-9a7a-eb5820da5a84)

As can be seen in the added red connections additional predecessor and successor connections to the bidirectional elements would be sufficient to remove the dead ends. Additionally, it might be necessary to set additional predecessor and successor connections in the opposite direction, as a bidirectional element can be traversed in both directions.

**Comment by benediktschwab** [comment]
As the traffic space (represented by the green line) originates from an OpenDRIVE lane of type bidirectional, I enhanced rtron to add predecessors and successors in both directions.

Your red connection (north-west) is denoting a lane change onto the opposing lane since the OpenDRIVE road reference line and center lane is running in between the two driving lanes. In the OpenDRIVE dataset, the lane is indeed a dead end (with no successor) and then restarts (with no predecessor).
Does this help you?
